Update requirements.txt
don't working node
Installing required Python packages...
WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 5.29.0 at https://files.pythonhosted.org/packages/ee/2e/cc46181ddce0940647d21a8341bf2eddad247a5d030e8c30c7a342793978/protobuf-5.29.0-cp38-abi3-manylinux2014_x86_64.whl (from https://pypi.org/simple/protobuf/) (requires-python:>=3.8))
Reason for being yanked: https://github.com/protocolbuffers/protobuf/issues/19430#issuecomment-2518458119
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hivemind 1.2.0.dev0 requires protobuf<5.28.0,>=3.12.2, but you have protobuf 5.29.0 which is incompatible.